### PR TITLE
Fix some compatibility bugs

### PR DESCRIPTION
**Pull request by 0xdwong**
- Create temporary folders and read files across platforms
- Optimize audio processing
- Add ".pyc", "AppData", and "work-dir" to .gitignore

### CODE REVIEW

**Comment by 0xdwong** [comment]
I optimized the code in the "WhisperASR.py" file, but I haven't tested it on the Windows platform. Could you please help me test it?

**Comment by zdd123456M** [comment]
你新加一个功能字幕重排


You add a new function of subtitle rearrangement

---Original---
From: ***@***.***&gt;
Date: Tue, Nov 26, 2024 15:00 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [WEIFENG2333/VideoCaptioner] Fix some compatibility bugs (PR #76)




 
I optimized the code in the "WhisperASR.py" file, but I haven't tested it on the Windows platform. Could you please help me test it?

**Review by WEIFENG2333 — APPROVED** [review]

**Comment by zdd123456M** [comment]
I hope the author can add a function to limit the length of subtitles

**Comment by zdd123456M** [comment]
希望作者能加个限制字幕长度功能
I hope the author can add a function to limit the length of subtitles








---Original---
From: ***@***.***&gt;
Date: Sun, Dec 1, 2024 22:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [WEIFENG2333/VideoCaptioner] Fix some compatibility bugs (PR #76)




 
@WEIFENG2333 approved this pull request.

**Comment by WEIFENG2333** [comment]
> 希望作者能加个限制字幕长度功能 I hope the author can add a function to limit the length of subtitles
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Dec 1, 2024 22:19 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [WEIFENG2333/VideoCaptioner] Fix some compatibility bugs (PR #76) @WEIFENG2333 approved this pull request. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;


Have been achieved.

**Comment by WEIFENG2333** [comment]
由于window里使用的是const-me版本的whisper-cpp，与正常的whisper-cpp有一些调用参数不同。已经修改相关代码可以适配两种版本的cpp。

**Pull request closed without merging**
