### PR TITLE
加入批量处理字幕文件及修改许多地方

### PR DESCRIPTION
**Pull request by philpw99**
批量处理字幕的功能是来自 ZENGXIANGXUAN ，在这只是做个搬运
然后自己越改越上瘾，修改了很多处，可能会给你带来一些头疼哟！
现在已经加入了FasterWhisper直接翻译成英语功能

### CODE REVIEW

**Comment by philpw99** [comment]
Well, I changed quite a lot of things in this program.
* Add an Enum Task.Type to distinguish each task type, instead of using Task.status
* Fix an annoying problem that causes transcript to fail at 99%.
* Batch processing will use work_dir as the working directory, but then the result will put in the original folder.
* Now most of the Open File dialog will remember the last open folder location.
* I am not a ASS fan, so I actually change the result to be .srt , but now thinking of it, I should change it back to ASS, because all the nice work you have done.
* Planning to add "Translate to English" in FastWhisper option. It will require no other API. All I need is English anyway.

**Comment by js79903** [comment]
批量翻译这功能实用,
我已经加入API接口了,
我已经有mp3和英文字幕了,
只能单个文件翻译.麻烦

**Comment by philpw99** [comment]
批量翻译的毛病是很容易把公益服务器挤爆。建议大家还是用自己的API KEY来做批量翻译，又或者干脆批量翻译功能只能用自己的API KEY来做。

**Comment by WEIFENG2333** [comment]
感谢贡献，目前精力有限，过两周会忙完后会陆续处理issure和pr的。

**Pull request closed without merging**
